### ISSUE TITLE
Audio help?

### ISSUE THREAD

**Issue by josh1244** [hteumeuleu/playorama#3]
I have got the video working just fine, but I cannot figure out how to get the wav into a pda file. I have tried exporting it in audacity as both wav and mp3 and changing the filetype to  pda, but neither work.

**Comment by hteumeuleu** [comment]
Hey there. Sorry for the delayed answer. The only proper way I know to encode `pda` right now is to include them in a Playdate project and compile it using the SDK. In the compiled `pdx` you'll get your audio files as `pda`. But I'm also working with my colleagues to get an online audio encoder in the upcoming months. Thanks!
